### PR TITLE
781 refine lyche scss

### PR DESCRIPTION
**Pull request by Snorre98**
Deals with: 
- https://github.com/Samfundet/Samfundet4/issues/863
- https://github.com/Samfundet/Samfundet4/issues/863

### CODE REVIEW

**Comment by magsyg** [comment]
pics pls

**Comment by Snorre98** [comment]
LycheHome_mobile

**Comment by Snorre98** [comment]
LycheAbout

**Comment by Snorre98** [comment]
LycheAbout_mobile

**Comment by Snorre98** [comment]
LycheContact

**Comment by Snorre98** [comment]
LycheContect_mobile

**Review by tiniuspre — APPROVED** [review]

**Review by robines — APPROVED** [review]
LGTM

**Pull request merged**
